---
title: "Incendios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library(tidyverse)
library(readxl)
library(sf)
library(lubridate)
library(data.table)
options(scipen = 99)

```

```{r}
#Cargamos y limpiamos el dataset de cantidad de incendios

cantidad <- read.csv("cantidad.csv", sep = ";")

str(cantidad)

cantidad <- cantidad %>%  #uno las columnas con gather para agrupar la data en tidy format
  #gather(key = "incendio_x_tipo",
   #      value = "cant_incendios_x_tipo",
    #     c(4:7)) %>% 
   rename(anio = incendio_anio) %>% 
  rename(provincia = incendio_provincia) %>% 
  arrange(anio) %>% 
  drop_na()
  

#cantidad <- cantidad %>% #renombro la variable
  #rename(anio = incendio_anio) %>% 
 # rename(provincia = incendio_provincia)

cantidad$provincia <- tolower(cantidad$provincia) #paso todo a minúscula
cantidad$provincia <- gsub(cantidad$provincia , pattern = " ", replacement = "_") #reemplazo espacios por _
cantidad$provincia <- gsub(cantidad$provincia , pattern = "río_negro", replacement = "rio_negro")
cantidad$provincia <- gsub(cantidad$provincia , pattern = "entre_ríos", replacement = "entre_rios")
cantidad$provincia <- gsub(cantidad$provincia , pattern = "córdoba", replacement = "cordoba")
cantidad$provincia <- gsub(cantidad$provincia , pattern = "neuquén", replacement = "neuquen")
cantidad$provincia <- gsub(cantidad$provincia , pattern = "santa_fé", replacement = "santa_fe")
cantidad$provincia <- gsub(cantidad$provincia , pattern = "ciudad_autónoma_de_buenos_aires", replacement = "caba")
cantidad$provincia <- gsub(cantidad$provincia , pattern = "tucumán", replacement = "tucuman")



unique(cantidad$provincia)

```

```{r}
#Cargamos y limpiamos el dataset de superficie afectada por incendios

superficie <- read.csv("superficie.csv", sep = ";")


str(superficie)

#superficie <- superficie %>%  #uno las columnas con gather para agrupar la data en tidy format
 # gather(key = "superficie_afectada_tipo",
  #       value = "superficie_afectada_ha",
   #      c(4:8))

superficie <- superficie %>% #renombro la variable
  rename(anio = superficie_afectada_por_incendios_anio) %>% 
  rename(provincia = superficie_afectada_por_incendios_provincia)

superficie$provincia <- tolower(superficie$provincia) #paso todo a minúscula
superficie$provincia <- gsub(superficie$provincia , pattern = " ", replacement = "_") #reemplazo espacios por _
superficie$provincia <- gsub(superficie$provincia , pattern = "río_negro", replacement = "rio_negro")
superficie$provincia <- gsub(superficie$provincia , pattern = "entre_ríos", replacement = "entre_rios")
superficie$provincia <- gsub(superficie$provincia , pattern = "córdoba", replacement = "cordoba")
superficie$provincia <- gsub(superficie$provincia , pattern = "neuquén", replacement = "neuquen")
superficie$provincia <- gsub(superficie$provincia , pattern = "santa_fé", replacement = "santa_fe")
superficie$provincia <- gsub(superficie$provincia , pattern = "ciudad_autónoma_de_buenos_aires", replacement = "caba")
superficie$provincia <- gsub(superficie$provincia , pattern = "tucumán", replacement = "tucuman")
superficie$provincia <- gsub(superficie$provincia , pattern = "tierra_del_fuego,_antártida_e_islas_del_atlántico_sur", replacement = "tierra_del_fuego")

unique(superficie$provincia)

```


```{r}
#Incorporamos dataset sobre tamaño de las provincias y  agregamos la columna al dataset de superficie afectada


tamanio_arg <- read.csv("tamanio_provincias.csv", sep = ";", encoding = "UTF-8")

str(tamanio_arg)

tamanio_arg$provincia <- tamanio_arg$X.U.FEFF.provincia

tamanio_arg$provincia <- tolower(tamanio_arg$provincia) #paso todo a minúscula
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = " ", replacement = "_") #reemplazo 
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = "río_negro", replacement = "rio_negro")
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = "entre_ríos", replacement = "entre_rios")
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = "córdoba", replacement = "cordoba")
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = "neuquén", replacement = "neuquen")
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = "santa_fé", replacement = "santa_fe")
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = "tucumán", replacement = "tucuman")
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = "ciudad_autónoma_de_buenos_aires", replacement = "caba")
tamanio_arg$provincia <- gsub(tamanio_arg$provincia , pattern = "tierra_del_fuego,_antártida_e_islas_del_atlántico_sur", replacement = "tierra_del_fuego")

tamanio_arg <- tamanio_arg %>% 
  select(!X.U.FEFF.provincia)

superficie <- tamanio_arg %>% left_join(superficie, by = "provincia")


unique(tamanio_arg$provincia)



superficie <- superficie %>% 
  mutate(ha_km2 = superficie_afectada_por_incendios_total_hectareas/100) %>% 
  mutate(sup_prop = round((ha_km2/km2)*100,2)) #Creamos la variable sup_prop para normalizar la prop de Ha afectadas, redondeamos a 2 decimales

max(superficie$sup_prop) #vemos si hay algún valor extraño (muy alto)
superficie %>% filter(sup_prop == 63.15) #corresponde a caba por lo que se trata de un error en los datos así que lo eliminamos
superficie <-superficie %>% filter(!sup_prop == 63.15)

```


```{r}
# Mapa de argentina

argentina <- st_read("https://raw.githubusercontent.com/aaizemberg/geo-data/gh-pages/ar/provincias_indec_2010.geojson")

str(argentina)

argentina <- argentina %>% 
  select(provincia, geometry) 

unique(argentina$provincia)

argentina$provincia <- tolower(argentina$provincia) #paso todo a minúscula
argentina$provincia <- gsub(argentina$provincia , pattern = " ", replacement = "_") #reemplazo espacios por _



cantidad_mapa <- argentina %>% left_join(cantidad, by="provincia") %>% 
  drop_na() %>% 
  arrange(anio)

superficie_mapa <- argentina %>% left_join(superficie, by = "provincia") %>% 
  drop_na() %>% 
  arrange(anio) 
  


```


```{r}
unique(superficie_mapa$provincia)
unique(argentina$provincia)
unique(superficie$provincia)
unique(cantidad$provincia)

```

```{r}
library(rsconnect)
```

